version: '3.8'

services: 
  web:
    build: .
    ports:
      - "8080:80"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "test123"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - db
    ports:
      - "8081:80"
    environment:
    - PMA_HOST=db
    - MYSQL_ROOT_PASSWORD="test123"
